# """
# Django settings for backend project.

# Generated by 'django-admin startproject' using Django 6.0.6.
# """

# from pathlib import Path
# import os
# import dj_database_url

# # ============================================================
# # BASE DIRECTORY
# # ============================================================

# BASE_DIR = Path(__file__).resolve().parent.parent


# # ============================================================
# # SECURITY
# # ============================================================

# SECRET_KEY = os.environ.get(
#     "SECRET_KEY",
#     "django-insecure-local-development-key"
# )

# # Local development defaults to True.
# # Render will use DEBUG=False from Environment Variables.
# DEBUG = os.environ.get("DEBUG", "True").lower() == "true"


# # ============================================================
# # ALLOWED HOSTS
# # ============================================================

# ALLOWED_HOSTS = [
#     "127.0.0.1",
#     "localhost",
#     "192.168.31.234",
# ]

# # Render automatically provides RENDER_EXTERNAL_HOSTNAME.
# if os.environ.get("RENDER"):
#     render_hostname = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

#     if render_hostname:
#         ALLOWED_HOSTS.append(render_hostname)


# # ============================================================
# # APPLICATIONS
# # ============================================================

# INSTALLED_APPS = [
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",

#     "rest_framework",
#     "corsheaders",

#     "accounts",
#     "restaurant",
#     "hotel",
#     "inventory",
#     "employees",
#     "reports",
#     "purchase",
# ]


# # ============================================================
# # MIDDLEWARE
# # ============================================================

# MIDDLEWARE = [
#     "corsheaders.middleware.CorsMiddleware",

#     "django.middleware.security.SecurityMiddleware",

#     "django.contrib.sessions.middleware.SessionMiddleware",

#     "django.middleware.common.CommonMiddleware",

#     "django.middleware.csrf.CsrfViewMiddleware",

#     "django.contrib.auth.middleware.AuthenticationMiddleware",

#     "django.contrib.messages.middleware.MessageMiddleware",

#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]


# # ============================================================
# # URL / WSGI
# # ============================================================

# ROOT_URLCONF = "backend.urls"

# WSGI_APPLICATION = "backend.wsgi.application"


# # ============================================================
# # TEMPLATES
# # ============================================================

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",

#         "DIRS": [],

#         "APP_DIRS": True,

#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",

#                 "django.contrib.auth.context_processors.auth",

#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]


# # ============================================================
# # DATABASE - MYSQL
# # ============================================================
# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.environ.get('DATABASE_URL')
#     )
# }


# # ============================================================
# # DJANGO REST FRAMEWORK
# # ============================================================

# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#     ),
# }


# # ============================================================
# # PASSWORD VALIDATION
# # ============================================================

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "UserAttributeSimilarityValidator"
#         ),
#     },

#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "MinimumLengthValidator"
#         ),
#     },

#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "CommonPasswordValidator"
#         ),
#     },

#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "NumericPasswordValidator"
#         ),
#     },
# ]


# # ============================================================
# # INTERNATIONALIZATION
# # ============================================================

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True

# USE_TZ = True


# # ============================================================
# # STATIC FILES
# # ============================================================

# STATIC_URL = "static/"

# STATIC_ROOT = BASE_DIR / "staticfiles"


# # ============================================================
# # CORS
# # ============================================================

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",

#     "http://127.0.0.1:3000",

#     "http://192.168.31.234:3000",

#     "https://smartdinepro-frontend.onrender.com",
# ]


# # ============================================================
# # CSRF
# # ============================================================

# CSRF_TRUSTED_ORIGINS = [
#     "https://smartdinepro-frontend.onrender.com",
# ]


# # ============================================================
# # DEFAULT PRIMARY KEY
# # ============================================================

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django.
"""

from pathlib import Path
import os
import dj_database_url


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-development-key"
)

DEBUG = os.environ.get("DEBUG", "True").lower() == "true"


# ============================================================
# ALLOWED HOSTS
# ============================================================

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "192.168.31.234",
]

# Render hostname
RENDER_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

if RENDER_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_HOSTNAME)


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "corsheaders",

    # SmartDine apps
    "accounts",
    "restaurant",
    "hotel",
    "inventory",
    "employees",
    "reports",
    "purchase",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL / WSGI
# ============================================================

ROOT_URLCONF = "backend.urls"

WSGI_APPLICATION = "backend.wsgi.application"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# DATABASE
# ============================================================

# Render:
# DATABASE_URL is supplied through Render Environment Variables.
#
# Local development:
# If DATABASE_URL is not available, SQLite will be used.

import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        env="DATABASE_URL",
        conn_max_age=600,
        ssl_require=True,
    )
}

# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


# ============================================================
# CORS
# ============================================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.31.234:3000",
    "https://smartdinepro-frontend.onrender.com",
]


# ============================================================
# CSRF
# ============================================================

CSRF_TRUSTED_ORIGINS = [
    "https://smartdinepro-frontend.onrender.com",
]


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"