# Generated by Django 6.0.6 on 2026-07-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Served', 'Served'), ('Billed', 'Billed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Occupied', 'Occupied'), ('Billing', 'Billing'), ('Cleaning', 'Cleaning')], default='Available', max_length=20),
        ),
    ]
