# Generated by Django 6.0.6 on 2026-06-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Cashier', 'Cashier'), ('Waiter', 'Waiter'), ('Chef', 'Chef'), ('Cleaner', 'Cleaner')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shift_time', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
